In [18]:
import numpy as np
import pandas as pd

In [19]:
data=pd.read_csv("heart.csv")

In [20]:
data

age  sex  chest_pain_type  resting_bp  cholestoral  fasting_blood_sugar  \
0     63    1                3         145          233                    1   
1     37    1                2         130          250                    0   
2     41    0                1         130          204                    0   
3     56    1                1         120          236                    0   
4     57    0                0         120          354                    0   
..   ...  ...              ...         ...          ...                  ...   
595   40    1                3         152          223                    0   
596   39    1                3         118          219                    0   
597   35    1                3         120          198                    0   
598   35    0                3         138          183                    0   
599   35    1                3         126          282                    0   

     restecg  max_hr  exang  oldpeak  slope  num_major_vessels  thal  target  
0          0     150      0      2.3      0                  0     1       1  
1          1     187      0      3.5      0                  0     2       1  
2          0     172      0      1.4      2                  0     2       1  
3          1     178      0      0.8      2                  0     2       1  
4          1     163      1      0.6      2                  0     2       1  
..       ...     ...    ...      ...    ...                ...   ...     ...  
595        0     181      0      0.0      0                  0     2       1  
596        0     140      0      1.2      1                  0     2       1  
597        0     130      1      1.6      1                  0     2       1  
598        0     182      0      1.4      0                  0     0       0  
599        2     156      1      0.0      0                  0     2       1  

[600 rows x 14 columns]

In [21]:
data.head()

age  sex  chest_pain_type  resting_bp  cholestoral  fasting_blood_sugar  \
0   63    1                3         145          233                    1   
1   37    1                2         130          250                    0   
2   41    0                1         130          204                    0   
3   56    1                1         120          236                    0   
4   57    0                0         120          354                    0   

   restecg  max_hr  exang  oldpeak  slope  num_major_vessels  thal  target  
0        0     150      0      2.3      0                  0     1       1  
1        1     187      0      3.5      0                  0     2       1  
2        0     172      0      1.4      2                  0     2       1  
3        1     178      0      0.8      2                  0     2       1  
4        1     163      1      0.6      2                  0     2       1

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   age                  600 non-null    int64  
 1   sex                  600 non-null    int64  
 2   chest_pain_type      600 non-null    int64  
 3   resting_bp           600 non-null    int64  
 4   cholestoral          600 non-null    int64  
 5   fasting_blood_sugar  600 non-null    int64  
 6   restecg              600 non-null    int64  
 7   max_hr               600 non-null    int64  
 8   exang                600 non-null    int64  
 9   oldpeak              600 non-null    float64
 10  slope                600 non-null    int64  
 11  num_major_vessels    600 non-null    int64  
 12  thal                 600 non-null    int64  
 13  target               600 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 65.8 KB


In [23]:
data.shape

(600, 14)

In [24]:
data.isnull().values.any()

False

In [25]:
data.isnull().sum()

age                    0
sex                    0
chest_pain_type        0
resting_bp             0
cholestoral            0
fasting_blood_sugar    0
restecg                0
max_hr                 0
exang                  0
oldpeak                0
slope                  0
num_major_vessels      0
thal                   0
target                 0
dtype: int64

In [26]:
X=data.drop(columns="target",axis=1)
Y=data['target']
data.isnull().sum()

age                    0
sex                    0
chest_pain_type        0
resting_bp             0
cholestoral            0
fasting_blood_sugar    0
restecg                0
max_hr                 0
exang                  0
oldpeak                0
slope                  0
num_major_vessels      0
thal                   0
target                 0
dtype: int64

In [27]:
print(X)

     age  sex  chest_pain_type  resting_bp  cholestoral  fasting_blood_sugar  \
0     63    1                3         145          233                    1   
1     37    1                2         130          250                    0   
2     41    0                1         130          204                    0   
3     56    1                1         120          236                    0   
4     57    0                0         120          354                    0   
..   ...  ...              ...         ...          ...                  ...   
595   40    1                3         152          223                    0   
596   39    1                3         118          219                    0   
597   35    1                3         120          198                    0   
598   35    0                3         138          183                    0   
599   35    1                3         126          282                    0   

     restecg  max_hr  exang  oldpeak  s

In [28]:
print(Y)

0      1
1      1
2      1
3      1
4      1
      ..
595    1
596    1
597    1
598    0
599    1
Name: target, Length: 600, dtype: int64


In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y, test_size=0.2,random_state=42)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(480, 13)
(120, 13)
(480,)
(120,)


In [30]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

# Random Forest algorithm
random_forest_classifier = RandomForestClassifier(n_estimators=10, criterion="entropy") 
random_forest_classifier.fit(X_train, Y_train)

# Logistic Regression algorithm
logistic_regression_model = LogisticRegression()
logistic_regression_model.fit(X_train, Y_train)


D:\New folder\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [31]:
y_pred= classifier.predict(X_test) 
y_pred

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [32]:
# 0=having no heart disease
# 1=having heart disease


In [33]:
accuracy_score=(Y_test,y_pred)
accuracy_score

(110    1
 419    0
 565    1
 77     1
 181    0
       ..
 399    1
 340    0
 148    1
 494    0
 439    1
 Name: target, Length: 120, dtype: int64,
 array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
        0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64))

In [34]:
# Assuming you have trained the Random Forest Classifier and saved it as 'rf_classifier'

import numpy as np

input_data = np.array([[57, 0, 1, 130, 236, 0, 0, 174, 0, 0, 1, 1, 2]])  # Input data as a 2D array

predicted_output = classifier.predict(input_data)

if predicted_output == 0:
    print("Person does not have heart disease.")
else:
    print("Person has heart disease.")


Person does not have heart disease.


D:\New folder\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [35]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(Y_test, y_pred)
cm

array([[50, 12],
       [20, 38]], dtype=int64)

In [36]:
# Specify the file path for saving the pickle file
import pickle
file_path = 'heart.pkl'

# Save the trained classifier as a pickle file
with open(file_path, 'wb') as file:
    pickle.dump(classifier, file)
